@echo off
echo Setting up project...
echo Initializing database...
docker compose exec crypto-agent python -c "from src.database import init_db; init_db()"
echo Setting up pgvector...
docker compose exec crypto-agent python -c "from src.database import setup_pgvector; setup_pgvector()"
echo Project setup complete!
