@echo off
echo Setting up project...
echo Initializing database...
docker compose exec crypto-agent bash -c "cd /app/src && python -c 'from database import init_db; init_db()'"
echo Setting up pgvector...
docker compose exec crypto-agent bash -c "cd /app/src && python -c 'from database import setup_pgvector; setup_pgvector()'"
echo Project setup complete!
